[2025-04-28 16:51:35] Iniciando bot...
Bot iniciado con PID: 14468
C:\xampp\htdocs\BOGOKER_V1.0\venv\Lib\site-packages\telegram\utils\request.py:49: UserWarning: python-telegram-bot is using upstream urllib3. This is allowed but not supported by python-telegram-bot maintainers.
  warnings.warn(
2025-04-28 16:51:58,124 - __main__ - INFO - Bot iniciado con PID 5800
2025-04-28 16:51:58,133 - apscheduler.scheduler - INFO - Scheduler started
2025-04-28 16:52:00,343 - __main__ - INFO - Bot escuchando. Usa Ctrl+C para detener.
2025-04-28 21:29:58,465 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24A9590>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-28 21:30:03,639 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24A9810>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-28 21:30:22,079 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24A9F90>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-28 21:30:42,416 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AA5D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-28 21:30:47,418 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AA710>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-28 21:31:05,661 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AAD50>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-28 21:31:10,663 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AAE90>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:57:16,202 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AB610>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:57:21,329 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AB4D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:57:26,377 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AB390>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:57:37,350 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AAFD0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:57:57,343 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AA990>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:58:09,333 - urllib3.connectionpool - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AA5D0>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:58:14,335 - urllib3.connectionpool - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AA490>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
2025-04-29 00:58:19,398 - urllib3.connectionpool - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000024BA24AA350>, 'Connection to api.telegram.org timed out. (connect timeout=5.0)')': /bot8041502880:AAEXID_fmek37Y4M388v6weF0s-2AFG6dnk/getUpdates
